//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/tcpapp/AppContext.msg.
//

#ifndef _APPCONTEXT_M_H_
#define _APPCONTEXT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/tcpapp/AppContext.msg</tt> by opp_msgc.
 * <pre>
 * packet AppContext{
 *     int appIndex; 
 *     int appId; 
 *     int portId; 
 *     int fileSize; 
 *     int remainingFileSize; 
 *     bool cxStatus = false; 
 *     int playBufferSize; 
 *     double txDuration; 
 *     int chunkSize; 
 *     double codecRate; 
 *     
 *     bool initialPlayStarted; 
 *     int userClass; 
 * }
 * </pre>
 */
class AppContext : public ::cPacket
{
  protected:
    int appIndex_var;
    int appId_var;
    int portId_var;
    int fileSize_var;
    int remainingFileSize_var;
    bool cxStatus_var;
    int playBufferSize_var;
    double txDuration_var;
    int chunkSize_var;
    double codecRate_var;
    bool initialPlayStarted_var;
    int userClass_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppContext&);

  public:
    AppContext(const char *name=NULL, int kind=0);
    AppContext(const AppContext& other);
    virtual ~AppContext();
    AppContext& operator=(const AppContext& other);
    virtual AppContext *dup() const {return new AppContext(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getAppIndex() const;
    virtual void setAppIndex(int appIndex_var);
    virtual int getAppId() const;
    virtual void setAppId(int appId_var);
    virtual int getPortId() const;
    virtual void setPortId(int portId_var);
    virtual int getFileSize() const;
    virtual void setFileSize(int fileSize_var);
    virtual int getRemainingFileSize() const;
    virtual void setRemainingFileSize(int remainingFileSize_var);
    virtual bool getCxStatus() const;
    virtual void setCxStatus(bool cxStatus_var);
    virtual int getPlayBufferSize() const;
    virtual void setPlayBufferSize(int playBufferSize_var);
    virtual double getTxDuration() const;
    virtual void setTxDuration(double txDuration_var);
    virtual int getChunkSize() const;
    virtual void setChunkSize(int chunkSize_var);
    virtual double getCodecRate() const;
    virtual void setCodecRate(double codecRate_var);
    virtual bool getInitialPlayStarted() const;
    virtual void setInitialPlayStarted(bool initialPlayStarted_var);
    virtual int getUserClass() const;
    virtual void setUserClass(int userClass_var);
};

inline void doPacking(cCommBuffer *b, AppContext& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AppContext& obj) {obj.parsimUnpack(b);}


#endif // _APPCONTEXT_M_H_
